package com.microservice.auth.presentation.controller;

import com.microservice.auth.persistence.model.enums.State;
import com.microservice.auth.presentation.dto.*;
import com.microservice.auth.presentation.dto.HTTP.MessageAuthDTO;
import com.microservice.auth.presentation.dto.HTTP.MessageDTO;
import com.microservice.auth.service.implementation.AuthServiceImpl;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/auth")
@CrossOrigin(origins = "http://localhost:4200")
@Tag(name = "Microservice Auth", description = "this microservice is in charge of handling security-related requests")
public class AuthController {


    final AuthServiceImpl authServiceImpl;
    public AuthController(AuthServiceImpl authServiceImpl) {
        this.authServiceImpl = authServiceImpl;
    }

    @PostMapping(value ="/login-client",produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "Login client",
            description = "this function is responsible for receiving user information, verifying the password and generating an access token. ",
            tags = {"Login", "Account", "Access"},
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Contain the information of client required for de process of log in ",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = LoginClientDTO.class
                            )
                    )
            ),
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "return a token of access",
                            content = @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = TokenDTO.class
                                    )
                            )

                    )
            }
    )
    public ResponseEntity<MessageAuthDTO<TokenDTO>> loginClient(@Valid @RequestBody LoginClientDTO loginClientDTO) throws Exception {
        TokenDTO token =  authServiceImpl.loginClient(loginClientDTO);
        return ResponseEntity.ok().body(new MessageAuthDTO<>(false, token));
    }

    @PostMapping(value = "/register-client",produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "Register client",
            description = "this function is responsible for receiving the user's information, verifying and saving it, and creating the account. ",
            tags = {"Login", "Account", "Access"},
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Contain the information of client required for de process of register ",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = RegisterClientDTO.class
                            )
                    )
            ),
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "return a state of operation",
                            content = @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = StateDTO.class
                                    )
                            )

                    )
            }
    )
    public ResponseEntity<MessageAuthDTO<StateDTO>> registerClient(@Valid @RequestBody RegisterClientDTO registerClientDTO)  {
        StateDTO stateRegister = authServiceImpl.registerClient(registerClientDTO);

        return ResponseEntity.ok().body(new MessageAuthDTO<>(false, stateRegister));
    }

    @PostMapping(value = "/activation-code")
    @Operation(
            summary = "Activation Account ",
            description = "This function is responsible for receiving the code generated by the registration, validating it and activating the account.  ",
            tags = {"Activation", "Account", "Access",""},
            parameters = {
                    @Parameter(
                            name = "code",
                            description = "is a code generated for de proccess of regisger",
                            required = true,
                            content = @Content(
                                    mediaType = "String",
                                    schema = @Schema(
                                            implementation = String.class
                                    )
                            )
                    ),
                    @Parameter(
                            name = "idUser",
                            description = "Is the Id of user that make a request",
                            required = true,
                            content = @Content(
                                    mediaType = "String",
                                    schema = @Schema(
                                            implementation = String.class
                                    )
                            )
                    )

            },
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "return a state of operation",
                            content = @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = State.class
                                    )
                            )

                    )
            }
    )
    public  ResponseEntity<MessageAuthDTO<State>> activeAccount (@RequestParam("code") String code , @RequestParam("idUser") String idUser)  {
        State stateActiveAccount = authServiceImpl.activationAccount(code,idUser);
        return ResponseEntity.ok().body(new MessageAuthDTO<>(false, stateActiveAccount));
    }

    @PostMapping(value = "/forgot-password")
    @Operation(
            summary = "Forgot password ",
            description = "this function is in charge of receiving the user's e-mail address and generates it, sends the access code.",
            tags = {"forgot", "Account", "Access","password"},
            parameters = {
                    @Parameter(
                            name = "emailAddress",
                            description = "is a email address of the user making the request",
                            required = true,
                            content = @Content(
                                    mediaType = "String",
                                    schema = @Schema(
                                            implementation = String.class
                                    )
                            )
                    ),
            },
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "return a state of operation",
                            content = @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = State.class
                                    )
                            )

                    )
            }
    )
    public  ResponseEntity<MessageDTO<State>> forgotPassword(@RequestParam("emailAddress") String emailAddress )  {
        State stateCodeForgotPsw = authServiceImpl.forgotPassword(emailAddress);
        if( stateCodeForgotPsw ==State.ERROR) {
            throw new IllegalArgumentException("El código de activación no se ha podido generar");
        }
        return ResponseEntity.ok().body(new MessageDTO<>(false, stateCodeForgotPsw));
    }

    @PostMapping(value = "/verify-code-forgot-password")
    @Operation(
            summary = "verify the code sent to recover the password ",
            description = "This function is responsible for receiving the code generated by the request forgotPassword and the email of user, validates y return a state of operation.  ",
            tags = {"Activation", "Account", "Access","check"},
            parameters = {
                    @Parameter(
                            name = "code",
                            description = "is a code generated for de process of forgotPassword",
                            required = true,
                            content = @Content(
                                    mediaType = "String",
                                    schema = @Schema(
                                            implementation = String.class
                                    )
                            )
                    ),
                    @Parameter(
                            name = "emailAddress",
                            description = "Is the emailAddress of user that make a request",
                            required = true,
                            content = @Content(
                                    mediaType = "String",
                                    schema = @Schema(
                                            implementation = String.class
                                    )
                            )
                    )

            },
            responses = {
                    @ApiResponse(
                            responseCode = "200",
                            description = "return a state of operation",
                            content = @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = State.class
                                    )
                            )

                    )
            }
    )
    public ResponseEntity<MessageDTO<State>> verifyCodeForgotPassword(@RequestParam("code") String code,@RequestParam("emailAddress") String emailAddress)  {
        State stateVerify = authServiceImpl.verifyForgotPassword(code,emailAddress);
        if( stateVerify == State.ERROR) {
            throw  new IllegalArgumentException("no se ha autorizado la solicitud");
        }
        return ResponseEntity.ok().body(new MessageDTO<>(false, stateVerify));
    }

    @PatchMapping("/change-password")
    @Operation(
            summary = "Change Password ",
            description = "This function is responsible for receiving the new password and the email address of user, verify password and und update the data in the data base.",
            tags = {"Activation", "Account", "Access","password","change", "update"},
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    description = "Contain the information of client required for de process of change the password (new password, email address)",
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(
                                    implementation = ChangePasswordDTO.class
                            )
                    )
            ),
            responses = {

                    @ApiResponse(
                            responseCode = "200",
                            description = "return a token access",
                            content = @Content(
                                    mediaType = "application/json",
                                    schema = @Schema(
                                            implementation = TokenDTO.class
                                    )
                            )

                    )
            }
    )
    public ResponseEntity<MessageDTO<TokenDTO>> changePassword(@RequestBody ChangePasswordDTO changePasswordDTO) {
        TokenDTO token = authServiceImpl.changePassword(changePasswordDTO);
        if(token ==null) {
            throw new IllegalArgumentException("No se ha autorizado la solicitud");
        }
        return ResponseEntity.ok().body(new MessageDTO<>(false,token));
    }
}
