eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: users
          uri: http://localhost:8082
          predicates:
            - Path=/api/manage-user/**