server:
  port: 8082

spring:
  application:
    name: msvc-manage-user
  data:
    mongodb:
      uri: mongodb+srv://mi-boleta:mi-boleta@mi-boleta.fixwk.mongodb.net/?retryWrites=true&w=majority&appName=mi-boleta
      database: mi-boleta
      password: mi-boleta
      username: mi-boleta

  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka