

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: auth
          uri: lb://msvc-auth
          predicates:
            - Path=/api/auth/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka