server:
  port: 8086

spring:
  application:
    name: msvc-pays

  eureka:
    instance:
      hostname: localhost
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka

security:
  token:
    access-token: TEST-2515610485462480-092921-6e68461ca9ba25ae748fe51fbf6cd7fc-1547178602
  tokenStripe:
    tokenSecret: sk_test_51Q5dZNFGVkZEhLlAvhLlMFqLWoLjbV4DHOoHaE1boCjRftEcyo2Y4KE4XGhCLkT49iaEiY6pKv1v274suVTwIuQ100Mr2iIONg
